// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_rEwLjTO5IoRjt1PpEDnGwV7zW6Kp2Xk',
    appId: '1:886092474300:web:dd33c3adb307d633412db9',
    messagingSenderId: '886092474300',
    projectId: 'moviesapp-8b594',
    authDomain: 'moviesapp-8b594.firebaseapp.com',
    storageBucket: 'moviesapp-8b594.appspot.com',
    measurementId: 'G-1JF3DPGE0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaubpwoyoBld4p8U_TJgitViQ-wpb8Pcc',
    appId: '1:886092474300:android:95ba658a2f045995412db9',
    messagingSenderId: '886092474300',
    projectId: 'moviesapp-8b594',
    storageBucket: 'moviesapp-8b594.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeUpDYQ7xcM0v1nRDzUfluaoQSo8raIng',
    appId: '1:886092474300:ios:62de6dd9ee1f6149412db9',
    messagingSenderId: '886092474300',
    projectId: 'moviesapp-8b594',
    storageBucket: 'moviesapp-8b594.appspot.com',
    iosBundleId: 'com.example.moviesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeUpDYQ7xcM0v1nRDzUfluaoQSo8raIng',
    appId: '1:886092474300:ios:62de6dd9ee1f6149412db9',
    messagingSenderId: '886092474300',
    projectId: 'moviesapp-8b594',
    storageBucket: 'moviesapp-8b594.appspot.com',
    iosBundleId: 'com.example.moviesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_rEwLjTO5IoRjt1PpEDnGwV7zW6Kp2Xk',
    appId: '1:886092474300:web:c66a088e6e1d3aad412db9',
    messagingSenderId: '886092474300',
    projectId: 'moviesapp-8b594',
    authDomain: 'moviesapp-8b594.firebaseapp.com',
    storageBucket: 'moviesapp-8b594.appspot.com',
    measurementId: 'G-6BZGYX111G',
  );
}
